### ISSUE TITLE
"Empty Folders" Isn't recursive

### ISSUE THREAD

**Issue by TheFrenchGhosty** [vaeth/bookmarkdupes#84] opened 2019-11-06 21:19 UTC
"Empty Folders" doesn't consider as empty, folders containing empty folders, the only way to detect them is to first remove/move the folders inside first.

It would be nice if it was recursive.

**Comment by vaeth** [comment] 2019-11-12 18:19
Dupe of #73

**Closed as completed by vaeth** 2019-11-12 18:19 UTC
Labels: duplicate
