### ISSUE TITLE
stripping descriptions problem

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#8] opened 2017-11-30 13:17 UTC
1
I thought "stripping descriptions" means something like "deleting descriptions", 
but it doesn't occur (in my case).

2
The addon freezes when this cleanup is complete (gray buttons, aren't clicked), 
so you need to turn off/on addon - to restore functionality.

my Firefox - 55.0.3 (x64).

**Comment by vaeth** [comment] 2017-11-30 14:49
Thanks a lot for the report! This is a serious regression!
It should be fixed now. I will make an emergency release immediately.

**Comment by perdolka** [comment] 2017-11-30 16:06
Thanks for the quick fix!
Another little problem (or not?) here -
bookmark with cleaned description jumps to 1 position up (in bookmark list Ctrl+B).

**Comment by vaeth** [comment] 2017-11-30 18:22
This does not happen here, but I can imagine that this happens if you have "strange" bookmarks in the folder in which you strip the description. (By "strange" I mean things which for some reason are not passed through the bookmark API).
It might also happen if you added a bookmark above the one you strip before you actually do the stripping.

The problem is that this "stripping" is actually not possible by the bookmark API (the bookmark API is not even able to check whether there does exist a description for the bookmark).
This "stripping" is done only with a trick: A new bookmark is created (with the data of the previous bookmark), and the old bookmark is removed. In order to create a new bookmark, it is necessary to specify the parent folder and entry number. The code just gets this parent and number from the bookmark API before displaying the bookmarks and remembers it until you press the button "list all bookmarks" again. So the information might be incorrect (if the bookmark API suppresses certain "special" bookmarks which are then not counted) or outdated (if you added a bookmark between displaying of bookmarks and removal).

**Comment by perdolka** [comment] 2017-11-30 18:28
OK, thanks for the explanation.

**Closed as completed** 2017-11-30 18:28 UTC
