### ISSUE TITLE
Rephrase to avoid ambiguity

### ISSUE THREAD

**Issue by anohren** [vaeth/bookmarkdupes#91] opened 2020-02-13 12:05 UTC
After doing a search I get "134 (of 753) dupes in 66 groups". I'm just assuming that it means "134 dupes of 753 total bookmarks in 66 groups".

The current wording makes it sound like I'm just viewing 134 out of a total of 753 dupes.

**Comment by vaeth** [comment] 2020-02-15 12:06
Thank you for your report.
The issue is fixed in the git repositories and will be released with the next version.

**Closed as completed by vaeth** 2020-02-15 12:06 UTC
